# Generated by Django 5.1.6 on 2025-03-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customuser_profile_image_athleteprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('round', models.IntegerField(default=1)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('athlete1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_athlete1', to='accounts.athleteprofile')),
                ('athlete2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_athlete2', to='accounts.athleteprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
        ),
    ]
