# Generated by Django 5.1.6 on 2025-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ipratingopinion'),
        ('tournaments', '0002_tournament_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='accounts.athleteprofile'),
        ),
    ]
