# Generated by Django 5.1.6 on 2025-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player_limit',
            field=models.IntegerField(choices=[(8, '8 players'), (16, '16 players')], default=8),
        ),
    ]
