# Generated by Django 5.1.6 on 2025-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='player_limit',
            field=models.IntegerField(choices=[(8, '8 pemain'), (16, '16 pemain')], default=8),
        ),
    ]
