# Generated by Django 5.1.6 on 2025-06-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_player_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score1',
            new_name='set1_p1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score2',
            new_name='set1_p2',
        ),
    ]
