# Generated by Django 5.1.6 on 2025-06-24 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_managers'),
        ('tournaments', '0008_match_set2_p1_match_set2_p2_match_set3_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('knockout', 'Sistem Gugur'), ('pool', 'Sistem Pool')], default='knockout', max_length=10, verbose_name='Tipe Turnamen'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_limit',
            field=models.IntegerField(choices=[(8, '8 pemain (Sistem Gugur)'), (12, '12 pemain (Sistem Pool)'), (16, '16 pemain (Sistem Gugur)'), (24, '24 pemain (Sistem Pool)')], default=8),
        ),
        migrations.CreateModel(
            name='TournamentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(related_name='tournament_pools', to='accounts.athleteprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Pool',
                'verbose_name_plural': 'Tournament Pools',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentpool'),
        ),
    ]
