# Generated by Django 5.1.6 on 2025-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_tournament_type_alter_match_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='stage',
            field=models.CharField(blank=True, choices=[('pool', 'Pool Stage'), ('knockout', 'Knockout Stage')], max_length=10, null=True),
        ),
    ]
