# Generated by Django 5.1.6 on 2025-07-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournament_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='stage',
            field=models.CharField(blank=True, choices=[('pool', 'Babak Pool'), ('knockout', 'Babak Gugur')], max_length=10, null=True),
        ),
    ]
