# Generated by Django 5.1.6 on 2025-03-06 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_image_athleteprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRatingOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_identifier', models.CharField(max_length=255)),
                ('opinion_rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_opinions', to='accounts.athleteprofile')),
                ('ip_account', models.ForeignKey(limit_choices_to={'role': 'ip'}, on_delete=django.db.models.deletion.CASCADE, related_name='rating_opinions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
