# Generated by Django 5.1.6 on 2025-03-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ipratingopinion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipratingopinion',
            unique_together={('ip_account', 'athlete')},
        ),
    ]
