# Generated by Django 5.1.6 on 2025-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ipratingopinion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(default='Temp name', max_length=100),
        ),
    ]
