# Generated by Django 5.1.6 on 2025-04-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='Temp nickname', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(default='Temp real name', max_length=100),
        ),
    ]
