# Generated by Django 5.1.6 on 2025-04-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_nickname_alter_customuser_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='previous_divisi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Divisi Sebelumnya'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ptm',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama PTM'),
        ),
        migrations.CreateModel(
            name='AthleteAccountReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('ptm', models.CharField(max_length=100, verbose_name='Nama PTM')),
                ('divisi', models.CharField(max_length=100, verbose_name='Divisi Sebelumnya')),
                ('sudah_ada_akun', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Referensi Akun Atlet',
                'verbose_name_plural': 'Referensi Akun Atlet',
                'unique_together': {('nickname', 'ptm')},
            },
        ),
    ]
