# Generated by Django 5.1.6 on 2025-05-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_email_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
